### ISSUE TITLE
Option to skip insertion of <style>...</style>?

### ISSUE THREAD

**Issue by jkorinth** [preftech/dash-tabulator#12]
It seems dash_tabulator_min.js always inserts the default style in the form of a <style> tag. Is there any way to stop it from doing that? It makes restyling the CSS really hard, because you have to sprinkle everything with !important.

**Comment by pjaol** [comment]
Could you show an example, might make it easier to track down
Not sure if it's something I did or upstream in react-tabulator or tabulator or even dash

**Comment by pjaol** [comment]
@jkorinth I've just added react-tabulator themes where you can specify in the dash-tabulator constructor one of the existing themes https://github.com/preftech/dash-tabulator#themes

There is also an option to turn off a theme by setting the theme parameter to ""
```
dash_tabulator.DashTabulator(
        id='tabulator',
        theme="",
        options=options,
        downloadButtonType=downloadButtonType,
        clearFilterButtonType=clearFilterButtonType,
    ),
```

[import 'react-tabulator/lib/styles.css']( https://github.com/ngduc/react-tabulator/blob/master/lib/styles.css)
is still included as it's a requirement for tabulator to work. But the main themes are now configurable.

**Comment by pjaol** [comment]
Assuming this is resolved
