### ISSUE TITLE
Customize table style

### ISSUE THREAD

**Issue by xanderwallace85** [preftech/dash-tabulator#15]
Hi @pjaol !
Is it possible to personalize the style of the table?

**Comment by pjaol** [comment]
Yes it is Tabulator has a lot of style options 
http://tabulator.info/docs/4.9/style 
and even themes http://tabulator.info/docs/4.9/theme

Simply add a custom css to your Dash assets directory or if using themes add the theme to the external style sheets

```python
external_stylesheets = ['https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css']
app = dash.Dash(__name__, external_scripts=external_scripts, external_stylesheets=external_stylesheets)

```
Tabulator is on unpkg's CDN, so you could choose a theme and then add it with the following base path
https://unpkg.com/tabulator-tables@4.1.4/dist/css

e.g. using the semantic-ui theme
```python
external_stylesheets = ['https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
                                        'https://unpkg.com/tabulator-tables@4.1.4/dist/css/semantic-ui/tabulator_semantic-ui.min.css']
app = dash.Dash(__name__, external_scripts=external_scripts, external_stylesheets=external_stylesheets)
```

**Comment by xanderwallace85** [comment]
> ```python
> /dist/css/semantic-ui/tabulator_semantic-ui.min.css
> ```

Hi @pjaol ! Thank you for the help! 
I cannot see how I can change the color of the highlighted rows/cells :( Could you please give an example to show me that? Thanks a lot!

**Comment by pjaol** [comment]
Hi @xanderwallace85 take a look at tabulator's style's documentation for rows on tabulator

http://tabulator.info/docs/4.0/style#css-rows
http://tabulator.info/docs/4.0/style#sass-rows

It's probably one of these :
* tabulator-cell 
* tabulator-editing 
* rowSelectedBackground 
* rowSelectedBackgroundHover
* editBoxColor


Specify an css override with the !important attribute

so 
assets/custom_tables.css
```css
.editBoxColor { background: gray !important }
```

You'll need to experiment to find that right one for your needs. 
Hope that helps!
