### ISSUE TITLE
Clarification regarding 'input'

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#18]
The docs mention that editable tables are possible provided the option `'editable': 'input'` is set in the columns.

Then the callbacks are supposed to look like this:

```
@app.callback(Output('output', 'children'), 
    [Input('input', 'rowClicked'),
    Input('input', 'cellEdited'),
    Input('input', 'dataChanged'), 
    Input('input', 'dataFiltering'),
    Input('input', 'dataFiltered')])
...
```

This callback is looking for a component with `id='input'` which, in the examples, is nowhere set. Is that internally set somehow?
Or is this the ID of the table object?

**Comment by pjaol** [comment]
@soerendip thanks this was a bug in the documentation, it should be resolved now, the id should have been 'tabulator'  I've updated it to 

```node
@app.callback(Output('output', 'children'), 
    [Input('tabulator', 'rowClicked'),
    Input('tabulator', 'cellEdited'),
    Input('tabulator', 'dataChanged'), 
    Input('tabulator', 'dataFiltering'),
    Input('tabulator', 'dataFiltered')])
```

The 'editor':'input'  is a tabulator setting, you can find a ton of built in options 
http://tabulator.info/docs/4.8/edit

The tabulator developer has done and amazing job with this, hopefully it's of use to you!
