### ISSUE TITLE
Suggestions for Filtering 

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#19]
The filtering could be more patient. I cannot type in a longer word, because the table updates before I can finish.
It also would be nice to leave the filtering expression there and not let it disappear so the user knows which filters are set. 
Cheers
Great extention though!!

**Comment by pjaol** [comment]
@soerendip the filter disappearing should be resolved now
For filter speed there is a tabulator option you can set headerFilterLiveFilterDelay in ms
```node
options = { 
              "headerFilterLiveFilterDelay":3000
......
               "groupBy": "col", 
               "selectable":"true"}
```
