### ISSUE TITLE
Suggestion: Downloaded data should contain empty string instead of 'null'

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#20]
Exporting the data in csv (probably also excel) format fills up missing values with 'null'. And a dataframe that contains 'null' becomes not None in the table view i.e. empthy. 

Therefore, it is not possible to have a dataframe with column values null, eins, zwei, drei. (German counting). And loading the exported data into pandas dataframe forces object type and leads to many issues downstream. First, you will have to import the data, then transform the 'null' strings to actually missing values. Then the whole column still has datatype string, so that needs to be cast to float if it is numeric values etc.

**Comment by pjaol** [comment]
@soerendip i'm not sure got this correct so forgive me if I misunderstood 

If you replace None's / null's / NaNs in your dataframe as "" that will replace the values in your csv or xlsx 
![image](https://user-images.githubusercontent.com/490072/103103822-d0f3b700-45f1-11eb-9145-ebdf1ff90b6e.png)

```python

@app.callback([ Output('tabulator', 'columns'),
                Output('tabulator', 'data'),
                Output('tabulator', 'initialHeaderFilter')],
                [Input('interval-component-iu', 'n_intervals')])
def initialize(val):
    d = [[1, "Oli Bob",None,None,None,None],[2,"Mary May", 1, None, None, "foo"]]
    df = pd.DataFrame(d, columns=["id", "name", "age", "col","dob","print" ])
    df.fillna(value="", inplace=True)
    print(df.dtypes)
    print(df.to_dict('records'))

    return columns, df.to_dict('records'), initialHeaderFilter
```

![image](https://user-images.githubusercontent.com/490072/103103827-d5b86b00-45f1-11eb-8ad7-23b927e8c470.png)

As the data is being marshalled between python and json it has to have a value, None -> null
The easiest way is as above using df.fillna or df.where

**Comment by soerendip** [comment]
You could, when exporting the dataframe to excel or csv exchange those values automatically and not leave it to the user.
Suggestion.

**Comment by pjaol** [comment]
@soerendip - this is a pretty heavy stack of items
```
Dash / Plotly
|_
    Dast-Tabulator (this)
    |_
       React-Tabulator (https://github.com/ngduc/react-tabulator)
       |_
          Tabulator (https://github.com/olifolkerd/tabulator)
          |_
              SheetJs (https://github.com/SheetJS/sheetjs)
```

I've just taken a mature component that's already ported to react and made dash compatible.
It's far from being perfect, just enough to meet my needs and the needs of some others, I hope you are getting use out of it. Will there be issues? Yes. All software has issues. 
This is open source that I'm doing in my spare time and encouraging others to contribute to, so we can improve it for everyone.
If you would like to improve it I highly suggest you take a look at 
Tabulator's download options
http://tabulator.info/docs/4.9/download

Some of the download call backs http://tabulator.info/docs/4.9/callbacks#download
downloadDataFormatter appears to provide some cell manipulation methods 
However these are client / browser side solutions that will be significantly slower than using a DataFrame over any large amounts of data.

To customize this code, you also have options
Fork the code (It's an MIT license) 
 - develop and test a solution
 - you are entitled to keep it for yourself or contribute back a solution with a pull request. 
    - I suggest contributing back, mainly because you can then get updates with your code included, nothing worse than being stuck on older versions of software that require resolving a problem over and over again.
