### ISSUE TITLE
TopCalc columns shifted

### ISSUE THREAD

**Issue by arthur-FD** [preftech/dash-tabulator#22]
Hello @pjaol,

Thank you very much for your work, this component has been of great help.

I am facing a bug regarding TopCalc columns which are shifted when I load the data.
However, as soon as I refresh the table by filtering or sorting by one columns, the sums align itself.

Would you how I could solve this issue?

Thank you for your help and time.

Best Regards,

Arthur

Shifted columns
![image](https://user-images.githubusercontent.com/75984752/103420409-e4bd9100-4b8e-11eb-8eca-da0d11a44f7a.png)

Fixed when refreshing the loaded table
![image](https://user-images.githubusercontent.com/75984752/103420443-0f0f4e80-4b8f-11eb-8c69-ff0c4537764a.png)

**Comment by arthur-FD** [comment]
Hello @pjaol,

Again, thank you for your work.

I found an other issue with the filtering when using nesting feature: it does not filter on child rows.

However I believe both of this issues are solved in the 4.8 release of tabulator.

React-tabulator is using this version since October, and you are using the latest version of it in your dependencies. So it should work as far as I understand.

Do you have an idea why we are still facing these issues?

Thank you again for your help and time.

Regards,

Arthur

**Comment by pjaol** [comment]
Sorry @arthur-FD I don't know why, can you link to the original issue and I'll see if I can follow the context?

**Comment by arthur-FD** [comment]
Thank you for coming back to me.

Regarding the original issue I mentioned - the topCalc shifted, an issue was raised and closed [here](https://github.com/olifolkerd/tabulator/issues/2507).

Regarding the filtering issue I mentioned, the fix is in the release note [here](http://tabulator.info/docs/4.8/release). You will find a screenshot below.
![image](https://user-images.githubusercontent.com/75984752/103696825-ee803380-4f96-11eb-9775-228ea2cf1cb5.png)

Arthur

**Comment by arthur-FD** [comment]
I tested with the last release of tabulator in a simple flask framework and it does not work either. So the bug must be on my side.
This is out of the boundaries of this repo, but here is my code. You might be able to spot something wrong.

![image](https://user-images.githubusercontent.com/75984752/103705705-6eac9600-4fa3-11eb-8c98-05ce91149534.png)

Thanks again,

Arthur

**Comment by arthur-FD** [comment]
Hello @pjaol 

In fact it was working, but not as I expected.

Sorry for that and thank you for your help

Arthur

**Comment by pjaol** [comment]
Sure - glad you were able to track it down!
