### ISSUE TITLE
Trigger a callback when clicking on a cell

### ISSUE THREAD

**Issue by arthur-FD** [preftech/dash-tabulator#24]
Hello @pjaol,

Thank you again for your work.

Is there a way to trigger a callback when clicking on a row?

I managed to do it with the row but can't find a way to do trigger the callback with the cell, even though there is callback for this in tabulator.

Thank you for your time and help!

Best Regards,

Arthur

**Comment by pjaol** [comment]
Hey @arthur-FD 

Yes it's possible, make sure you've got the latest version of dash-tabulator as this thing is changing frequently
Also ensure you have dash_extensions installed
```bash
pip install dash-tabulator -U
pip install dash_extensions
```
I've put together a quick example of it in a playground https://github.com/pjaol/dash-tabulator-playground

https://github.com/pjaol/dash-tabulator-playground/blob/2e0b9db852dc10b54d514d328552c1f24e41ef0c/playground.py#L58

And the example JS that goes with it
https://github.com/pjaol/dash-tabulator-playground/blob/main/assets/playground.js

**Comment by arthur-FD** [comment]
Thank your answer @pjaol and for having taken the time to come up with an example.

I understand that you used a javascript callback, but I am trying to trigger a python callback: I want to trigger some data processing in python when clicking on a particular cell.

I apology if it was not clear in my first post.

Thank you for your help.

Best regards.

Arthur

**Comment by pjaol** [comment]
Oh in that case in the JS function use the table.props.setProps method 

```js
cellLog: function (e, cell, table) {
             table.props.setProps({"cellClick" : JSON.stringify(cell)})
}
```

and in your python code

```python
@app.callback(
                          Output('output', 'children'), 
                          [Input('tabulator', 'cellClick')]
                         )
def cellClick(cellClick) :
      ..........
      return ..... 
```

**Comment by arthur-FD** [comment]
I will try that :)

Thank you so much

Arthur
