### ISSUE TITLE
If filters are active the corresponding fields should not be empty. 

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#26]
Sometimes people type accidentally into the filter fields and then they end up with an empty table. Leaving them confused and turning their back on the app, because they don't understand the logic, which is not obvious. 

I think, if filters are active the corresponding field should not be empty but should show the current state. Whatever the user typed. Then it is more clear why the table is empty or reduced.

**Comment by pjaol** [comment]
Update to the latest version of dash-tabulator, this was resolved in #17 

```
pip install dash-tabulator -U
```

**Comment by soerendip** [comment]
Works!!
