### ISSUE TITLE
Select all rows on filtered table should only select filter-passing rows.

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#28]
I am using a selection column:

        { "formatter": "rowSelection", "titleFormatter":"rowSelection", 
          "hozAlign":"center", "headerSort": False, "width":"1px", 'frozen': True}]

When the table is filtered for a subset of records and the row selection in the header is selected it seems that all records in the table are selected even the ones that are not visible (filtered out). 

Is there a way to only select the rows that pass the filter instead?

**Comment by pjaol** [comment]
This appears to be related to https://github.com/olifolkerd/tabulator/issues/2617
I tried the suggested fix of adding titleFormatterParams and it appears to work

```python
columns = [ {
        "formatter":"rowSelection", 
        "titleFormatter":"rowSelection", 
        "titleFormatterParams": {
               "rowRange": "active" # only toggle the values of the active filtered rows
         },
         "hozAlign":"center", 
         "headerSort":"false"
        },


```

**Comment by soerendip** [comment]
Yes that works! You are incredible.
