### ISSUE TITLE
Feature suggestion. Navigation with arrow keys and or Enter upon edit.

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#29]
I am not sure how easy that would be to implement, however, it would make interaction with the table faster.

Instead of having to click on each column to edit, after clicking enter upon edit, the next row could be selected. 

And/or row selection with the keyboard would be nice. E.g. pressing shift and arrow up/down.

There are probably more pressing issues than this though.

**Comment by pjaol** [comment]
Try the keybindings options from tabulator, I'm not sure if they're in react-tabulator 
http://tabulator.info/docs/4.8/keybindings
