### ISSUE TITLE
topCal custom function

### ISSUE THREAD

**Issue by arthur-FD** [preftech/dash-tabulator#32]
Hello @pjaol :)

I am trying to add a custom function to the topCalc feature in tabulator.

I tried using Namespace and adding for each column dictionary: ```'topCalc'=ns('freeze')``` - I instantiated ns as ```ns = Namespace("myNamespace", "tabulator")```. But nothing happens when doing so. I don't even see the JS logs in my console. Do you spot something obvious I am doing wrong?
You can see below my JavaScript. I am trying to reproduce what Oli did in this issue: https://github.com/olifolkerd/tabulator/issues/498.

![image](https://user-images.githubusercontent.com/75984752/106794974-6bafce80-6651-11eb-9c8a-334425fecd8a.png)

Thank you very much for your time and help.

Best regards,

Arthur

**Comment by pjaol** [comment]
Hey @arthur-FD 

It looks like I need to add topCalc / bottomCalc to here
https://github.com/preftech/dash-tabulator/blob/c28b44a83d49be434eca5de230bb2b4a0cb08a36/src/lib/components/DashTabulator.react.js#L105

I'll take a stab at it tomorrow and see I can also come up with a way to map any attribute of the heading similar to options

**Comment by arthur-FD** [comment]
Thanks a lot @pjaol !

I will try that on my side.

Best Regards,

Arthur

**Comment by arthur-FD** [comment]
Hello @pjaol

I hope you are well

I digged into the JS and I don't understand why this property is not working but the "formatter" property is working as in your example.

From my understanding, you are not doing anything additional with this "formatter" property. The loop you point to me there should resolve all the props we input

[(https://github.com/preftech/dash-tabulator/blob/c28b44a83d49be434eca5de230bb2b4a0cb08a36/src/lib/components/DashTabulator.react.js#L105)]

Could you hint me on what I should add to make this work?

Thank you very much @pjaol 

Arthur

**Comment by pjaol** [comment]
@arthur-FD sorry for taking so long - this should now be available 
just do a 
```sh
pip -U dash_tabulator
```

And you should be able to access custom JS functions from the columns settings 
An example of usage is
https://github.com/preftech/dash-tabulator/blob/e7022203e8cd03e8946b0a3861ee1295cdb83f6a/usage.py#L36

And 
https://github.com/preftech/dash-tabulator/blob/e7022203e8cd03e8946b0a3861ee1295cdb83f6a/assets/custom_tabulator.js#L16

**Comment by arthur-FD** [comment]
Hello @pjaol,

Thank you very much it looks great!

I have tested it and it works well.

However, it doesn't work when you have grouped columns - the feature I have included below. I tested it with a custom function returning a fixed value.

![image](https://user-images.githubusercontent.com/75984752/109486030-42c90080-7a7a-11eb-8776-4b5e96ae04ed.png)

I am not sure yet if it comes from the dash component or from tabulator itself. I will dig into into it

Best,

Arthur

**Comment by pjaol** [comment]
I'm going to close this issue out, feel free to open a new one if it turns out to be a different dash-tabulator issue. 
I'm still learning all the items that have to be enabled to make it as compatible as possible.

The one thing to bare in mind is dash-tabulator is built on react-tabulator which is built / based on tabulator.
So it could be an issue in that chain, I also got notifications on react-tabulator releasing a new update, it looks like a minor update but I'll take a look at upgrading that when I have a moment
