### ISSUE TITLE
Unable to get dataChanged to give the state on moveRow

### ISSUE THREAD

**Issue by ishi-xibo** [preftech/dash-tabulator#8]
hi there - I love this package. Wondering if you can help fix this: In my application, I need to be able to allow for drag and move of the rows of the table. To enable this, I have created 2 buttons - 
1. one for beginning the move: this works well as I dynamically change the options to set 'movableRows': True

2. One for ending the row move by reversing the above and saving the new table. However, I am unable to get the new table back. I tried getting the State of dataChanged but getting an empty set back. 

Appreciate any insights here.

**Comment by pjaol** [comment]
@ishi-xibo I've just added javascript resolution on tabulator options
https://github.com/preftech/dash-tabulator#javascript

I think if you use this with http://tabulator.info/docs/4.8/callbacks#column
You should be able to create a JS function that triggers when a column is moved

create a file in your assets folder
```javascript
window.myNamespace = Object.assign({}, window.myNamespace, {
    tabulator: {
        columnMoved: function (column, table) {
            console.log("Column is resized");
            console.log(column)
            // table.props.setProps({"columnMoved": ....})
        }
    }
});
```

Add dash_extensions to your python env 
```sh
pip install dash_extensions
```

```
from dash_extensions.javascript import Namespace
...
ns = Namespace("myNamespace", "tabulator")
...
options = {"columnMoved" : ns("columnMoved")}

```

I included an example with columnResized but I found that for some reason that table.props.setProps(...) worked the first time, but required selecting another column to work a second time. I suspect it's maintaining state and only updating when a change occurs. 
You also have to be careful about the table re-rendering and resetting your layout, take a look at how I managed rowSelected 
https://github.com/preftech/dash-tabulator/blob/ebc5af09a5a8b1dca0019151230bd00b650dcea9/src/lib/components/DashTabulator.react.js#L38

Let me know if this helps

**Comment by pjaol** [comment]
from reading the setProps they're only sent when there's a change in the prop, thus requiring clicking another column to make a second call. So it seems to be working as designed with plotly.
