### ISSUE TITLE
Register a callback when selecting all rows in a dash tabulator

### ISSUE THREAD

**Issue by AMpkusms** [preftech/dash-tabulator#9]
Hi there, I have got a tabulator with its first column defined as follows
` 
 {
        "formatter": "rowSelection",
        "titleFormatter": "rowSelection",
        "hozAlign": "center",
        "headerSort": False,
        "width": 10,
        "field": ""
    },
`
so that my tabulator looks like this

![GitHubQuestion](https://user-images.githubusercontent.com/53906377/100332278-29905e00-300c-11eb-8a2d-37b05280156b.png)

Now I can select all rows by clicking on the first column of title as in the image, but I'm wondering how to trigger a callback by this selecting all event and be noticed all the rows that I selected.

Many thanks.

**Comment by pjaol** [comment]
@AMpkusms this should now work for you, take a look at 
https://github.com/preftech/dash-tabulator/#multiple-row-selection

**Comment by pjaol** [comment]
This appears to be working, I've also fixed an issue with editing a cell when using multiple select. 
Let me know if you run into any issues
